- name: Add port 6443/tcp
  firewalld:
     port: 6443/tcp
     permanent: yes
     state: enabled
     immediate: yes
- name: Add port 2379-2380/tcp
  firewalld:
     port: 2379-2380/tcp
     permanent: yes
     state: enabled
     immediate: yes
- name: Add port 10250/tcp
  firewalld:
     port: 10250/tcp
     permanent: yes
     state: enabled
     immediate: yes
- name: Add port 10251/tcp
  firewalld:
     port: 10251/tcp
     permanent: yes
     state: enabled
     immediate: yes
- name: Add port 10252/tcp
  firewalld:
     port: 10252/tcp
     permanent: yes
     state: enabled
     immediate: yes
- name: Add port 10255/tcp
  firewalld:
     port: 10255/tcp
     permanent: yes
     state: enabled
     immediate: yes
- name: Reload firewall-cmd
  command: firewall-cmd --reload
- name: Kubeadm config
  command: kubeadm config images pull
- name: Permitir acceso desde workers
  firewalld:
     rich_rule: rule family=ipv4 source address=10.0.1.11/24 accept
     permanent: yes
     state: enabled
     immediate: yes
- name: Permitir acceso desde contenedores
  firewalld:
     rich_rule: rule family=ipv4 source address=172.17.0.0/16 accept
     permanent: yes
     zone: public
     state: enabled
     immediate: yes
- name: Reload firewall-cmd
  command: firewall-cmd --reload
- name: Reset kubeadm
  command: kubeadm reset -f
- name: Install kubeadm y definir red de PODs
  command: kubeadm init --pod-network-cidr 192.169.0.0/16
  register: command_out
- debug: msg="{{command_out.stdout}}"
- name: Crear directorio .kube
  file:
    path: /root/.kube
    state: directory
- name: Copy admin.conf a .kube/config
  command: cp /etc/kubernetes/admin.conf /root/.kube/config
- name: Permisos a config
  shell: 'chown $(id -u):$(id -g) /root/.kube/config'
