- hosts: worker.local
  vars_files:
     - group_vars/commons.yaml
  gather_facts: no
  remote_user: ansible
  become: true
  tasks:
   - name: Add port 10250/tcp
     firewalld:
        port: 10250/tcp
        permanent: yes
        state: enabled
        immediate: yes
   - name: Add port 30000-2380/tcp
     firewalld:
        port: 30000-32767/tcp
        permanent: yes
        state: enabled
        immediate: yes
        zone: public
   - name: Reload firewall-cmd
     command: firewall-cmd --reload
   - name: Unir al cluster de kubernetes
     command: "{{kubeadm_join}}"
