- name: Add br_netfilter to kernel
  modprobe:
     name: br_netfilter
     state: present
- name: Active transparent masquerade
  firewalld:
     masquerade: yes
     state: enabled
     permanent: yes
     immediate: yes
- name: Reload firewall-cmd
  command: firewall-cmd --reload
- name: Crear fichero k8s.conf
  file:
    path: /etc/sysctl.d/k8s.conf
    state: touch
- name: Permitir manejo de cortafuegos por kubernetes
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    state: present
    line: "{{ item }}"
  with_items:
  - 'net.bridge.bridge-nf-call-ip6tables = 1'
  - 'net.bridge.bridge-nf-call-iptables = 1'
- name: Disabled swap
  command: swapoff -a
- name: Desmontar arranque swap
  replace:
     path: /etc/fstab
     regexp: "/dev/mapper/cl-swap"
     replace: "#/Eliminar linea dev/mapper/cl-swap"
- name: Daemon Reload
  systemd:
      daemon_reload: yes
- name: Add docker repo
  command: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
- name: Install docker
  dnf:
    name: docker-ce-19.03.14.-3.el8
    state: present
- name: Docker Enabled and Start
  systemd:
    name: docker
    state: started
    enabled: yes
- name: Crear fichero kubernetes.repo
  file:
    path: /etc/yum.repos.d/kubernetes.repo
    state: touch
- name: Configurar repositorio de kubernetes
  lineinfile:
     path: /etc/yum.repos.d/kubernetes.repo
     state: present
     line: "{{ item }}"
  with_items:
  - '[kubernetes]'
  - 'name=Kubernetes'
  - 'baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64'
  - 'enabled=1'
  - 'gpgcheck=1'
  - 'repo_gpgcheck=1'
  - 'gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg'
  - 'exclude=kubelet kubeadm kubectl'
- name: Kubernetes install
  dnf:
    name: "{{ kube_rpms }}"
    disable_excludes: kubernetes
    state: present
- name: Kubernetes Enabled and Start
  systemd:
    name: kubelet
    state: started
    enabled: yes
