- hosts: master.local
  gather_facts: no
  remote_user: adminUsername
  become: true
  tasks:
   - name: Install Tigera
     command: kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml
     ignore_errors: yes
   - name: Download definition file
     get_url:
       url: https://docs.projectcalico.org/manifests/custom-resources.yaml
       force: yes
       dest: /home/ansible/DevOpsPR2/ansibleLocal
   - name: Cambiar cidr
     replace:
        path: /home/ansible/DevOpsPR2/ansibleLocal/custom-resources.yaml
        regexp: "192.168.0.0"
        replace: "192.169.0.0"
   - name: Install Callico
     command: kubectl apply -f custom-resources.yaml
