- name: Create user kubeadmin
  user:
     name: kubeadmin
     state: present
     password: "{{ kubeadmin_pass | password_hash('sha512')}}"
- name: Create dir /home/kubeadmin/.kube
  file:
     path: /home/kubeadmin/.kube
     state: directory
- name: Copy admin.conf a .kube/config
  command: cp /etc/kubernetes/admin.conf /home/kubeadmin/.kube/config
- name: Permisos a config
  shell: 'chown kubeadmin. /home/kubeadmin/.kube/config'
- name: Configurar repositorio de kubernetes
  lineinfile:
     path: /etc/sudoers.d/kubeadmin
     state: present
     create: yes
     line: "ALL ALL=(ALL) NOPASSWD: ALL"
